### ISSUE TITLE
Add a boolean enabling CDN for faster&cheaper hosting

### ISSUE THREAD

**Issue by unbrice** [DandyDev/pelican-bootstrap3#120]
While having Bootstrap CSS&JS bundled with the theme eases local development, it is suboptimal for a variety of reasons:
- Files are less unlikely to be in the browser cache
- Files are unlikely to be close to the user
- Certain popular hosting options (eg Amazon S3) don't compress files making the site slow on mobile
- On custom hosting this consumes bandwidth

In my case, these files represent [most of the weight of what a client has to fetch](https://redbot.org/?descend=True&uri=http://vleu.net).

I would like to add a boolean option that when set to True make ressources be fetched from well-established CDN:
- Bootstrap, Fontawesome and themes from [bootstrapcdn.com/](http://www.bootstrapcdn.com/)
- jQuery from [Google Hosted Libraries](https://developers.google.com/speed/libraries/devguide#jquery)

One could then set this boolean to True in publishconf.py to decrease cost and improve performances on the production site.
Is it something you'd accept to merge?

**Comment by DandyDev** [comment]
@unbrice any updates on this?

**Comment by dmsimard** [comment]
This would be a great feature! Any updates ?

**Comment by DonDebonair** [comment]
Hi!

First of all, thanks for your interest in this theme! It's with heavy heart that I have decided that I can no longer maintain this theme due to lack of time and changing interests. To makes sure the theme lives on however and not goes to waste, I've donated it to the [Pelican community](https://github.com/getpelican/pelican-themes). It can now be found in the official [pelican-themes repository](https://github.com/getpelican/pelican-themes/tree/master/pelican-bootstrap3). I'd suggest you re-submit your issue  there.

Sorry for the inconvenience!
