### ISSUE TITLE
Make Banner title optional

### ISSUE THREAD

**Issue by jtrip** [DandyDev/pelican-bootstrap3#140]
I didn't want to have my sitename on the banner, by default it would be too big and repetitive. But i did like the more subdued subtitle style. It could just be changed in css, but I like the flexibility I added. I understand if you feel otherwise.

What I did was update the banner template be like this:
```
    {% if BANNER_TITLE_FLAG %}
        <h1>
            {{ BANNER_TITLE }}
        </h1>
    {% endif %}
    {% if BANNER_SUBTITLE %}
        <p class="intro" style='margin-bottom:0px; margin-left:0px;'>
            {{ BANNER_SUBTITLE }}
        </p>
    {% endif %}
```
I don't know much about jinja2 variables so not sure if we could get away with just having BANNER_TITLE. If it is not set would it return False?

You might also noticed I changed the intro class margin here, not sure where else it is used but it was bothering me in the banner.

**Comment by cranmer** [comment]
I submitted #185

**Comment by MatthewGilbert** [comment]
If I try these solutions with an empty flag, or even simpler (since I do not want a title) something like

    <style>
        #banner{
            background-image:url("{{ SITEURL}}/{{ BANNER }}");
        }
    </style>
    <div id="banner">
        <div class="container{% if BOOTSTRAP_FLUID %}-fluid{% endif %}">
            <div class="copy">
            </div>
        </div>
    </div>

I am still getting an empty black box, e.g.

![test](https://cloud.githubusercontent.com/assets/2401026/9622030/1a41cadc-50fc-11e5-9aef-d4e7ca7b5bf4.png)

Does anyone have a work around for this?

**Comment by DonDebonair** [comment]
Hi!

First of all, thanks for your interest in this theme! It's with heavy heart that I have decided that I can no longer maintain this theme due to lack of time and changing interests. To makes sure the theme lives on however and not goes to waste, I've donated it to the [Pelican community](https://github.com/getpelican/pelican-themes). It can now be found in the official [pelican-themes repository](https://github.com/getpelican/pelican-themes/tree/master/pelican-bootstrap3). I'd suggest you re-submit your issue  there.

Sorry for the inconvenience!
