### ISSUE TITLE
Refactoring base template for easier implementation

### ISSUE THREAD

**Issue by goanpeca** [DandyDev/pelican-bootstrap3#150]
Hi :), happy new year

Great work on this template. We plan to use it for the new [Spyder](http://code.google.com/p/spyderlib/) website, and during this process I came up with some ides for improvements.

**Menu active element generation**
The current navbar does not create the "active" class for links defined on the MENUITEMS. 

**Base template**
I like your template a lot, but not everyone is just making blogs and I think is good that Pelican leaves that area of only for blogs... Even if it is not offered as such, everything in Pelican is leaning towards a Blog. 

For our use case the blog is just one section with other features/dowbnloads/documentation pages that follow a different look, so in this way I refactored the base templates so that the sidebar is not enforced from there, but only in the other pages. I understand there might some "code duplication" but this would leave more freedom for use in non blogging sites.

The idea is that the base template has only a block for the actual body content, whatever it might be, and then the other pages defined either a sidebar (blogs, articles) or a features set page that is different.

Just wanted to share some thoughts

Cheers!

**Comment by DandyDev** [comment]
Thanks for your interest in this theme! I feel honoured that you are considering using this theme for Spyder :) Thanks as well for all your thoughts and ideas. I will leave this issue open and look at your ideas in more detail in the coming weeks.

The menu active problem is something that was already on my todo-list, so I'll definitely be working on that. For the rest, feel free to contribute Pull Requests if you want. Otherwise, as said, I will take on these issues myself at some point :)

**Comment by goanpeca** [comment]
Thanks for the reply...

Menu
====
Since I am using only MENU_ITEMS for the menu entries... this is what I did so far to get the active menu generation working.

```
        <div class="collapse navbar-collapse navbar-ex1-collapse">
            <ul class="nav navbar-nav navbar-right">
                {% for title, link in MENUITEMS %}
                    {% set stripped_link = link|replace('/', '', 1)%}
                    {% if stripped_link in output_file %}
                        {% set link_state = 'class="active"' %}
                    {% else %}
                        {% set link_state = '' %}
                    {% endif %}
                    <li {{link_state}}><a href="{{ link }}">{{ title }}</a></li>
                {% endfor %}
                {% if DISPLAY_PAGES_ON_MENU %}
                    {% for p in PAGES %}
                         <li{% if p == page %} class="active"{% endif %}><a href="{{ SITEURL }}/{{ p.url }}">
                             {{ p.menulabel|default(p.title) }}
                          </a></li>
                      {% endfor %}
                {% endif %}
```

This assumed that the menu_label and slug was defined in the page, like:
menulabel: Features
slug: features

Maybe you can use as inspiration for a better solution ;)

Base templates
============
For this the changes I made a second template called `base_sidebar.html` (that inherits from `base.html`), so that the `base.html` had an empty content block, not enforcing the sidebar. So you could inherit from **base** and have an empty block to go nuts with bootstrap (maybe using html directly instead of mk or rst) or or you can inherit from **base_sidebar** and it would work as it is now.

I think it would be nice to have both options for users so on top of this I also created a page_2.html template that has no sidebar on it, so you can choose the template to use for non blog pages... **page** with sidebar... or **page_2** without.

Cheers!

**Comment by DonDebonair** [comment]
Hi!

First of all, thanks for your interest in this theme! It's with heavy heart that I have decided that I can no longer maintain this theme due to lack of time and changing interests. To makes sure the theme lives on however and not goes to waste, I've donated it to the [Pelican community](https://github.com/getpelican/pelican-themes). It can now be found in the official [pelican-themes repository](https://github.com/getpelican/pelican-themes/tree/master/pelican-bootstrap3). I'd suggest you re-submit your issue  there.

Sorry for the inconvenience!
