### ISSUE TITLE
Pagination breaking up

### ISSUE THREAD

**Issue by goanpeca** [DandyDev/pelican-bootstrap3#155]
Hi again :)

On the test site I am using pretty urls and pagination patterns, so...

```python
CATEGORIES_URL =  'categories/' 
CATEGORY_URL = 'categories/{slug}/'
CATEGORY_SAVE_AS = '{0}index.html'.format(CATEGORY_URL)
CATEGORIES_SAVE_AS = 'categories/index.html'

TAGS_URL = 'tags/'  
TAG_URL = 'tags/{slug}/'
TAG_SAVE_AS = '{0}index.html'.format(TAG_URL)
TAGS_SAVE_AS = 'tags/index.html'

PAGINATION_PATTERNS = (
    (1, '{base_name}/', '{base_name}/index.html'),
    (2, '{base_name}/page/{number}/', '{base_name}/page/{number}/index.html'),
)
```

And well, pagination under this circumstances is breaking up for categories and tags, the links in the page numbers on the bottom lead to wrong not existing urls.

While I think of a fix on the template I reverted to using th epager (older ...newer)

Cheers

**Comment by DonDebonair** [comment]
Hi!

First of all, thanks for your interest in this theme! It's with heavy heart that I have decided that I can no longer maintain this theme due to lack of time and changing interests. To makes sure the theme lives on however and not goes to waste, I've donated it to the [Pelican community](https://github.com/getpelican/pelican-themes). It can now be found in the official [pelican-themes repository](https://github.com/getpelican/pelican-themes/tree/master/pelican-bootstrap3). I'd suggest you re-submit your issue  there.

Sorry for the inconvenience!
