### ISSUE TITLE
Add support for period_archives.html templates

### ISSUE THREAD

**Issue by goanpeca** [DandyDev/pelican-bootstrap3#156]
Maybe this was omitted on purpose but it would be great to include by default the template to handle  

[├── period_archives.html  // to display time-period archives](http://docs.getpelican.com/en/3.5.0/themes.html)

as triggered by [these settings](http://docs.getpelican.com/en/3.5.0/settings.html#url-settings) in pelican

```python
YEAR_ARCHIVE_SAVE_AS = 'posts/{date:%Y}/index.html'
MONTH_ARCHIVE_SAVE_AS = 'posts/{date:%Y}/{date:%b}/index.html'
```

**Comment by DonDebonair** [comment]
Hi!

First of all, thanks for your interest in this theme! It's with heavy heart that I have decided that I can no longer maintain this theme due to lack of time and changing interests. To makes sure the theme lives on however and not goes to waste, I've donated it to the [Pelican community](https://github.com/getpelican/pelican-themes). It can now be found in the official [pelican-themes repository](https://github.com/getpelican/pelican-themes/tree/master/pelican-bootstrap3). I'd suggest you re-submit your issue  there.

Sorry for the inconvenience!
