### ISSUE TITLE
Custom CSS in Tipue search page 

### ISSUE THREAD

**Issue by cranmer** [DandyDev/pelican-bootstrap3#188]
I added a custom.css to make the search look nicer (see: http://diana-hep.github.io).
That works, but the search.html page doesn't include the custom css.
I'm not sure yet if that's an issue with that plugin or the theme.

**Comment by DandyDev** [comment]
You caught a bug, so thanks for that! The Tipue css was included twice on the search page, overriding the custom.css. Should be fixed now :)

**Comment by cranmer** [comment]
After this change the page is styled correctly, but the search results all point to "undefined". 
Previously the search results worked, it just had a css problem.
In the mean time, I added a custom URL to the github pages hosting. Now the site is at http://diana-hep.org/ -- I'm not sure if there is an issue with hosting on github pages with a custom URL. 
The tipue JSON on the server points to urls are of the form `http://diana-hep.org/{page}`
The source is here: https://github.com/diana-hep/diana-hep.github.io-source .  
Any ideas?

**Comment by DandyDev** [comment]
> Does
https://github.com/DandyDev/pelican-bootstrap3/blob/master/templates/search.html#L20
need {{SITEURL}} as in this example?

Not that I know of. I did change the search behaviour a bit though: https://github.com/DandyDev/pelican-bootstrap3/commit/bf0a77ede4263dc4cc1af9ae774519601891025c
People were complaining that the search action pointed to the hard-coded endpoint `/search`, which would only work if you had the right `.htaccess` rewrite rule(s). I now changed it so it can be configured using the `SEARCH_URL` setting. By default it now points to `/search.html` so that it works in development mode.

If you depended - like me - on `/search` working, you can fix it by adding this to your settings:

```
SEARCH_URL = '/search'
```

Hope that helps!

**Comment by cranmer** [comment]
I'll try. I'm still Not sure why it broke.
