### ISSUE TITLE
Reordering the sidebar

### ISSUE THREAD

**Issue by dmark** [DandyDev/pelican-bootstrap3#192]
Is there some way to reorder the elements in the sidebar or is this something that can be engineered? I assume right now it depends on the order of the elements in sidebar.html. Adding the ability to specify the order of the sidebar sections sounds like a lot of work, but I'm not an expert with this stuff. Happy to lend a hand if I can.

**Comment by DonDebonair** [comment]
Hi!

First of all, thanks for your interest in this theme! It's with heavy heart that I have decided that I can no longer maintain this theme due to lack of time and changing interests. To makes sure the theme lives on however and not goes to waste, I've donated it to the [Pelican community](https://github.com/getpelican/pelican-themes). It can now be found in the official [pelican-themes repository](https://github.com/getpelican/pelican-themes/tree/master/pelican-bootstrap3). I'd suggest you re-submit your issue  there.

Sorry for the inconvenience!
