### ISSUE TITLE
Chance of translation of template texts

### ISSUE THREAD

**Issue by mpancorbo** [DandyDev/pelican-bootstrap3#199]
When you write a blog in other language than English it is a mess to change all those small texts that templates push out: *Tags, Category, Categories, Links, Social,.." etc. And also some other bigger texts, such as the one at the footer.

I suggest to change all these appearances by a construction: `{{ TAGS_TEXT | default('Tags') }}`

So, if the user defines the variable `TAGS_TEXT` it is used instead of rutinary *Tags*. The same can be applied to similar texts.

**Comment by DonDebonair** [comment]
Hi!

First of all, thanks for your interest in this theme! It's with heavy heart that I have decided that I can no longer maintain this theme due to lack of time and changing interests. To makes sure the theme lives on however and not goes to waste, I've donated it to the [Pelican community](https://github.com/getpelican/pelican-themes). It can now be found in the official [pelican-themes repository](https://github.com/getpelican/pelican-themes/tree/master/pelican-bootstrap3). I'd suggest you re-submit your issue  there.

Sorry for the inconvenience!
