### ISSUE TITLE
Question about using tique_search

### ISSUE THREAD

**Issue by shanpy** [DandyDev/pelican-bootstrap3#205]
I tried to use tique_search, but after I put `DIRECT_TEMPLATES = (('search',))` in my `pelicanconf.py` file, I noticed after I did `make html`, no `index.html` file in output folder.

I can generate `index.html` after I comment this line or I do `DIRECT_TEMPLATES = ('index', 'categories', 'authors', 'archives', 'search')`. However, after I doing search, I found all url for search result is "undefined". 

Is there something that I was doing wrong?

Thank you!

**Comment by noshita** [comment]
The problem was solved by replacing pelican-bootstrap3/static/tipuesearch by Tipue Search v5.0's.
pelican-bootstrap3 uses Tipue Search v4.0.
I do not know why, but it works in my env.

**Comment by mlissner** [comment]
Can confirm issue and can confirm solution. Dropping in v5 of tipue search fixed the issue for me.

**Comment by DonDebonair** [comment]
Hi!

First of all, thanks for your interest in this theme! It's with heavy heart that I have decided that I can no longer maintain this theme due to lack of time and changing interests. To makes sure the theme lives on however and not goes to waste, I've donated it to the [Pelican community](https://github.com/getpelican/pelican-themes). It can now be found in the official [pelican-themes repository](https://github.com/getpelican/pelican-themes/tree/master/pelican-bootstrap3). I'd suggest you re-submit your issue  there.

Sorry for the inconvenience!
