### ISSUE TITLE
Path to sidebar image

### ISSUE THREAD

**Issue by J-Moravec** [DandyDev/pelican-bootstrap3#206]
Sidebar image takes different path on pages and categories. This result in not loading properly.

    SIDEBAR_IMAGES = ["images/image.png"]

on main page, it is loaded correctly, however on other pages, the search path is actually:

    pages/images/image.png

or

    category/images/image.png

**Comment by rubenvarela** [comment]
Looks like it's using a relative path to the folder you're in instead of to the root of the page.

Have you checked if adding a `/` at the beginning solves it?

Change 

    SIDEBAR_IMAGES = ["images/image.png"]

to

    SIDEBAR_IMAGES = ["/images/image.png"]

**Comment by DonDebonair** [comment]
Hi!

First of all, thanks for your interest in this theme! It's with heavy heart that I have decided that I can no longer maintain this theme due to lack of time and changing interests. To makes sure the theme lives on however and not goes to waste, I've donated it to the [Pelican community](https://github.com/getpelican/pelican-themes). It can now be found in the official [pelican-themes repository](https://github.com/getpelican/pelican-themes/tree/master/pelican-bootstrap3). I'd suggest you re-submit your issue  there.

Sorry for the inconvenience!
