### ISSUE TITLE
Add Category as a class of <body>

### ISSUE THREAD

**Issue by rubenvarela** [DandyDev/pelican-bootstrap3#208]
I'm working on a new site and for easier theming, it's really handy to have the category in the body class. 

In order to achieve this, in `templates/base.html` I changed the line that reads `<body>` to:

    <body{% if category %} class='{{category}}' {% endif %}>

I don't know if this is something that others would feel is useful/handy, so I'm not sure if I should submitting a Pull Request.

**Comment by DonDebonair** [comment]
Hi!

First of all, thanks for your interest in this theme! It's with heavy heart that I have decided that I can no longer maintain this theme due to lack of time and changing interests. To makes sure the theme lives on however and not goes to waste, I've donated it to the [Pelican community](https://github.com/getpelican/pelican-themes). It can now be found in the official [pelican-themes repository](https://github.com/getpelican/pelican-themes/tree/master/pelican-bootstrap3). I'd suggest you re-submit your issue  there.

Sorry for the inconvenience!
