### ISSUE TITLE
PAGES got removed in master

### ISSUE THREAD

**Issue by ingwinlu** [DandyDev/pelican-bootstrap3#210]
sup @DandyDev, hope you are doing well

as a heads up, `PAGES` for templates got removed from master yesterday: http://pelican.readthedocs.org/en/latest/faq.html#since-i-upgraded-pelican-my-pages-are-no-longer-rendered

**Comment by DandyDev** [comment]
hmmmm it seems I really need to put some work into this again. I will upgrade my Pelican install to the latest and test stuff out. Thanks for the headsup!

**Comment by DonDebonair** [comment]
Hi!

First of all, thanks for your interest in this theme! It's with heavy heart that I have decided that I can no longer maintain this theme due to lack of time and changing interests. To makes sure the theme lives on however and not goes to waste, I've donated it to the [Pelican community](https://github.com/getpelican/pelican-themes). It can now be found in the official [pelican-themes repository](https://github.com/getpelican/pelican-themes/tree/master/pelican-bootstrap3). I'd suggest you re-submit your issue  there.

Sorry for the inconvenience!
