### ISSUE TITLE
Disqus comment count script is loaded if displaying comments is disabled

### ISSUE THREAD

**Issue by marwinxxii** [DandyDev/pelican-bootstrap3#217]
I noticed, that Disqus comment count script is included in web page if DISQUS_DISPLAY_COUNTS is False. I think this is redundant and script should not be included in this case.

**Comment by DonDebonair** [comment]
Hi!

First of all, thanks for your interest in this theme! It's with heavy heart that I have decided that I can no longer maintain this theme due to lack of time and changing interests. To makes sure the theme lives on however and not goes to waste, I've donated it to the [Pelican community](https://github.com/getpelican/pelican-themes). It can now be found in the official [pelican-themes repository](https://github.com/getpelican/pelican-themes/tree/master/pelican-bootstrap3). I'd suggest you re-submit your issue  there.

Sorry for the inconvenience!
