### ISSUE TITLE
Can't show disqus comments

### ISSUE THREAD

**Issue by hendiko** [DandyDev/pelican-bootstrap3#219]
I have set `DISQUS_SITENAME = 'beautifulcloud'`, it works when I apply pelican-elegant theme, and I switch to pelican-bootstrap3, it has always shown info below: 

`We were unable to load Disqus. If you are a moderator please see our troubleshooting guide.`

My pelican version is 3.6.2.

**Comment by xuehao** [comment]
Hi @hendiko ,
I meet the same troubleshooting yesterday. I just find the solution a second ago.
The `disqus_url` is not right (Maybe the reason is that you set the variable `RELATIVE_URLS` to `True`).
So please define a new parameter in your config file like this:
`DISQUSURL = 'http://blog.yourdomain.com'`
Then, go to `pelican-bootstrap3` folder, edit `templates/includes/comments.html`.
Find the codes `var disqus_url = '{{ SITEURL }}/{{ article.url }}';`
Change `SITEURL` to `DISQUSURL` that you defined a minute ago.

**Comment by hendiko** [comment]
Thanks, you are right, it works now!!!

**Comment by yangjin-unique** [comment]
Hi @xuehao,
Per your comment, If we let 
SITEURL = 'http://blog.yourdomain.com',
Does this also fix this issue without modify templates/includes/comments.html ?
I tried, but failed.

**Comment by CubeSyVal** [comment]
The solution doesn't work in pelican's theme "Elegant".

If you use elegant, the most popular theme for pelican follow xuehao's guide but then go to templates/_includes/comments.html

On line 9, change 
{% set url = SITEURL+ '/' + article.url %}
to
{% set url = DISQUSURL+ '/' + article.url %}

instead.
