### ISSUE TITLE
Square FontAwesome icons exemption and custom icons

### ISSUE THREAD

**Issue by sfahmy** [DandyDev/pelican-bootstrap3#221]
At present the theme has a list of non-square icon exemptions and all others are assumed to have a square version. With the addition of the feature to choose a custom icon as the third parameter in the SOCIAL variable, this breaks too often as the vast majority of icons do not have a square version. I am trying to use graduation-cap for Google Scholar for example. Wouldn't it make more sense to flip the priority now, so there's a check for a list of icons for which a known square exists, while the others are all passed as-is? Otherwise the ability to specify an icon is pretty much useless. I'm suggesting the following inversion, which I am happy to submit as a pull request if you think it makes sense:

```
{% if name_sanitized in ['behance', 'bitbucket', 'facebook', 'foursquare', 'git', 'github', 'google-plus', 'linkedin', 'pinterest', 'reddit', 'rss', 'tumblr', 'twitter', 'vimeo', 'youtube'] %}
    {% set iconattributes = '"fa fa-' ~ name_sanitized ~ '-square fa-lg"' %}
{% else %}
    {% set iconattributes = '"fa fa-' ~ name_sanitized ~ ' fa-lg"' %}
```

**Comment by DonDebonair** [comment]
Hi!

First of all, thanks for your interest in this theme! It's with heavy heart that I have decided that I can no longer maintain this theme due to lack of time and changing interests. To makes sure the theme lives on however and not goes to waste, I've donated it to the [Pelican community](https://github.com/getpelican/pelican-themes). It can now be found in the official [pelican-themes repository](https://github.com/getpelican/pelican-themes/tree/master/pelican-bootstrap3). I'd suggest you re-submit your issue  there.

Sorry for the inconvenience!
