### ISSUE TITLE
enabling pelican-bootstrap3 affects 'codehilite' extension in MD_EXTENSIONS

### ISSUE THREAD

**Issue by alexanderwaldin** [DandyDev/pelican-bootstrap3#223]
If I have pelican-bootstrap3 enabled, syntax highlighting works fine as long as I don't define the MD_EXTENSIONS variable myself in pelicanconf.py

However, if I set the variable to:

    MD_EXTENSIONS = ['codehilite', 'extra']

the output is not highlighted. Perhaps it can't find the appropriate css, as the language identifiers are being stripped out, e.g.

:::python
def hello():
    print "Hello, World!"

becomes
def hello():
    print "Hello, World!"

there just is not any syntax highlighting.

**Comment by DonDebonair** [comment]
Hi!

First of all, thanks for your interest in this theme! It's with heavy heart that I have decided that I can no longer maintain this theme due to lack of time and changing interests. To makes sure the theme lives on however and not goes to waste, I've donated it to the [Pelican community](https://github.com/getpelican/pelican-themes). It can now be found in the official [pelican-themes repository](https://github.com/getpelican/pelican-themes/tree/master/pelican-bootstrap3). I'd suggest you re-submit your issue  there.

Sorry for the inconvenience!
