### ISSUE TITLE
Wiki

### ISSUE THREAD

**Issue by rubenvarela** [DandyDev/pelican-bootstrap3#228]
Hope you don't mind. I created a wiki with a page that list the variables I could find and some basic information on them.

I listed everything using headers (#'s) that way it can be copied and used on a configuration file for Pelican and titles there will be comments.

**Comment by lameei** [comment]
Good job. Appreciated.

**Comment by DonDebonair** [comment]
Hi!

First of all, thanks for your interest in this theme! It's with heavy heart that I have decided that I can no longer maintain this theme due to lack of time and changing interests. To makes sure the theme lives on however and not goes to waste, I've donated it to the [Pelican community](https://github.com/getpelican/pelican-themes). It can now be found in the official [pelican-themes repository](https://github.com/getpelican/pelican-themes/tree/master/pelican-bootstrap3). I'd suggest you re-submit your issue  there.

Sorry for the inconvenience!
