### ISSUE TITLE
Tipue search box pinned to top of viewport

### ISSUE THREAD

**Issue by fxer** [DandyDev/pelican-bootstrap3#253]
Looks like when using a Bootswatch theme the search box from Tipue is stuck at the top of the viewport, it doesn't center itself in the navbar like say, the Archives button does:

![searchbox](https://cloud.githubusercontent.com/assets/1500269/14228651/77a959f2-f8d0-11e5-8645-9e13e2b95d87.png)

There are two _**li**_ elements, one for search one for Archives, and while the Archives _**li**_ takes up the whole navbar the Search one does not. I'm not sure the correct css method for centering the search box in the navbar but this nasty hack in my custom.css at least makes it look ok for now:

```
/* Search box suck at top of viewport without this */
.navbar-search { margin-top: 8px; }
```

Using Tipue v5, Bootswatch paper theme

**Comment by DonDebonair** [comment]
Hi!

First of all, thanks for your interest in this theme! It's with heavy heart that I have decided that I can no longer maintain this theme due to lack of time and changing interests. To makes sure the theme lives on however and not goes to waste, I've donated it to the [Pelican community](https://github.com/getpelican/pelican-themes). It can now be found in the official [pelican-themes repository](https://github.com/getpelican/pelican-themes/tree/master/pelican-bootstrap3). I'd suggest you re-submit your issue  there.

Sorry for the inconvenience!
