### ISSUE TITLE
Word-break isn't cross-browser compatible

### ISSUE THREAD

**Issue by DandyDev** [DandyDev/pelican-bootstrap3#73]
See discussion in https://github.com/DandyDev/pelican-bootstrap3/pull/48

**Comment by DonDebonair** [comment]
Hi!

First of all, thanks for your interest in this theme! It's with heavy heart that I have decided that I can no longer maintain this theme due to lack of time and changing interests. To makes sure the theme lives on however and not goes to waste, I've donated it to the [Pelican community](https://github.com/getpelican/pelican-themes). It can now be found in the official [pelican-themes repository](https://github.com/getpelican/pelican-themes/tree/master/pelican-bootstrap3). I'd suggest you re-submit your issue  there.

Sorry for the inconvenience!
